version: '3'

services:
  voting.api:
    image: votingapi
    build:
      context: .
      dockerfile: Voting.API/Dockerfile
    environment:
      REDIS: votingdb
      RABBITMQ: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password

  voting.processor:
    image: votingprocessor
    build:
      context: .
      dockerfile: Voting.Processor/Dockerfile
    environment:
      REDIS: votingdb
      RABBITMQ: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
    depends_on:
      - rabbitmq
    # links: 
    #   - voting.rabbit
    restart: on-failure


  voting.webpy:
    image: votingwebpy
    build:
      context: ./Voting.Webpy/
      dockerfile: Dockerfile    
    environment:
      LOCAL: ""
      API_ADDRESS: "voting.api"
    ports:
        - "80:5000"

# additional services

  votingdb:
    image: redis
    environment:
      API_ADDRESS: "votingdb.api"
    ports:
        - "6379:6379"

  rabbitmq:
    image: library/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
      API_ADDRESS: "rabbitmq.api"
    ports:
      - "5672:5672"
    #  - "15672:15672"
    #healthcheck:
     # test: ["CMD", "curl", "-f", "http://localhost:15672"]
      #interval: 30s
      #timeout: 10s
      #retries: 5